version: "3.3"
services:
  workspace:
    container_name: saintcon-password-cracking
    image: cleeb/saintcon-password-cracking:latest
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    deploy:
      resources:
        reservations:
          devices:
            - count: 1
              capabilities: [gpu]